@ParametersAreNonnullByDefault @MethodsReturnNonnullByDefault
package com.simibubi.create.content.contraptions.components.structureMovement.glue;

import javax.annotation.ParametersAreNonnullByDefault;
