"project_id_env": "CROWDIN_PROJECT_ID"
"api_token_env": "CROWDIN_PERSONAL_TOKEN"
"base_path": "."

"preserve_hierarchy": true

"files": [
    {
        "source": "src/generated/resources/assets/create/lang/en_us.json",
        "translation": "src/main/resources/assets/create/lang/%locale_with_underscore%.json",
        "languages_mapping": {
            "locale_with_underscore": {
                "cs": "cs_cz",
                "da": "da_dk",
                "de": "de_de",
                "es-CL": "es_cl",
                "es-ES": "es_es",
                "es-MX": "es_mx",
                "fr": "fr_fr",
                "it": "it_it",
                "ja": "ja_jp",
                "ko": "ko_kr",
                "nl": "nl_nl",
                "pl": "pl_pl",
                "pt-BR": "pt_br",
                "pt-PT": "pt_pt",
                "ro": "ro_ro",
                "ru": "ru_ru",
                "th": "th_th",
                "uk": "uk_ua",
                "zh-CN": "zh_cn",
                "zh-TW": "zh_tw",
            }
        }
    }
]
