"project_id_env": "CROWDIN_PROJECT_ID"
"api_token_env": "CROWDIN_PERSONAL_TOKEN"
"base_path": "."

"preserve_hierarchy": true

"files": [
    {
        "source": "src/generated/resources/assets/create/lang/en_us.json",
        "translation": "src/main/resources/assets/create/lang/%locale_with_underscore%.json",
        "languages_mapping": {
            "locale_with_underscore": {
                "ar": "ar_sa",
                "be": "be_by",
                "bel": "bel_tr",
                "bg": "bg_bg",
                "cs": "cs_cz",
                "cy": "cy_gb",
                "da": "da_dk",
                "de": "de_de",
                "el": "el_gr",
                "en-GB": "en_gb",
                "eo": "eo_uy",
                "es-CL": "es_cl",
                "es-ES": "es_es",
                "es-MX": "es_mx",
                "et": "et_ee",
                "eu": "eu_es",
                "fa": "fa_ir",
                "fi": "fi_fi",
                "fr": "fr_fr",
                "fr-CA": "fr_ca",
                "hr": "hr_hr",
                "hu": "hu_hu",
                "hy-AM": "hy_am",
                "id": "id_id",
                "is": "is_is",
                "it": "it_it",
                "ja": "ja_jp",
                "kk": "kk_kz",
                "ko": "ko_kr",
                "ksh": "ksh",
                "lol": "lol_us",
                "lzh": "lzh",
                "nl": "nl_nl",
                "no": "no_no",
                "pl": "pl_pl",
                "pt-BR": "pt_br",
                "pt-PT": "pt_pt",
                "ro": "ro_ro",
                "rpr": "rpr",
                "ru": "ru_ru",
                "sv-SE": "sv_se",
                "th": "th_th",
                "tok": "tok",
                "tr": "tr_tr",
                "uk": "uk_ua",
                "vi": "vi_vn",
                "zh-CN": "zh_cn",
                "zh-TW": "zh_tw",
            }
        }
    }
]
