pluginManagement {
    repositories {
        if (providers.gradleProperty("create.useMavenLocal").isPresent()) {
            mavenLocal()
        }
        gradlePluginPortal()
        maven { url = "https://maven.neoforged.net/releases" }
    }
}

if (providers.gradleProperty("create.useLocalPonderComposite").isPresent() && file("Ponder").exists()) {
    includeBuild(".")
    includeBuild("Ponder") {
        dependencySubstitution {
            substitute(module("net.createmod.ponder:ponder-neoforge")).using(project(":neoforge"))
            substitute(module("net.createmod.ponder:ponder-common")).using(project(":common"))
        }
    }
}

rootProject.name = "$mod_id-$minecraft_version"
