# Configuration for Label Actions - https://github.com/dessant/label-actions

# ----------------------------------- ISSUES ----------------------------------- #

'env: fabric':
    issues:
        close: true
        close-reason: 'not planned'
        comment: >
            **Fabric Loader**: This issue tracker is only for the Forge/NeoForge versions of Create. Since you mentioned using Fabric Loader, please reopen this issue on the [Create Fabric issue tracker](https://github.com/Fabricators-of-Create/Create/issues). Thanks!

'env: hybrid server':
    issues:
        close: true
        close-reason: 'not planned'
        comment: >
            **Hybrid Server Software**: Create cannot reasonably support hybrid server software, such as [MohistMC](https://mohistmc.com/), as their changes under the hood make it difficult for larger mods to function properly. If you encounter this issue on official Forge/NeoForge server software, feel free to open a new issue. Otherwise, consider reporting this issue to the hybrid server software you are using. Thanks!

'env: outdated create version':
    issues:
        close: true
        close-reason: 'not planned'
        comment: >
            **Outdated Create Version**: Since you are using an outdated Create version, please update to the latest version as it may resolve your issue. If this issue persists after updating Create, feel free to open a new issue. Thanks!

'env: pojav':
    issues:
        close: true
        close-reason: 'not planned'
        comment: >
            **Pojav**: Create does not support Pojav or other mobile launchers due to rendering limitations. If you encounter this issue on a PC, feel free to open a new issue. Thanks!

'env: unsupported minecraft version':
    issues:
        close: true
        close-reason: 'not planned'
        comment: >
            **Unsupported Minecraft Version**: Unsupported Minecraft versions no longer receive Create updates. Please check the [supported Minecraft versions](https://github.com/Creators-of-Create/Create/wiki/dev.status). If you encounter this issue on a supported Minecraft version, feel free to open a new issue. Thanks!

# ----------------------------------- PULL REQUESTS ----------------------------------- #

'pr status: conflicts':
    prs:
        comment: >
            @{issue-author}, this pull request has merge conflicts with the target branch. Please merge the latest changes and leave a message here so we can continue with the process of reviewing and merging this pull request. Thanks!

'pr status: waiting for author':
    prs:
        comment: >
            @{issue-author}, a developer has left a review and requested changes. Please make the requested changes or further discuss them with the developer so this pull request can be merged. Thanks!

'pr status: wrong target':
    prs:
        comment: >
            @{issue-author}, this pull request is targeting the wrong branch. Pull requests should target the branch corresponding to the earliest supported Minecraft version unless the changes are specific to code that only exists for a newer Minecraft version. Please change the target branch, resolve any merge conflicts, and leave a message here so we can continue with the process of reviewing and merging this pull request. Thanks!
