name: I found a bug!
description: Report some other kind of issue.
labels: [ "type: bug" ]
body:
    -   type: textarea
        attributes:
            label: Description
            description: "
            Please describe the issue with as much detail as possible.
            Explain what happened, and what should have happened instead.
            Add screenshots or videos if they would be useful."
        validations:
            required: true

    -   type: input
        attributes:
            label: Game Log
            description: "
            We need the game's log file to see if there's any information there.
            This file can be found in the \"logs\" folder of your Minecraft folder as \"latest.log\".
            Please upload the file to https://mclo.gs/ and put the link here.
            "
        validations:
            required: true

    -   type: textarea
        attributes:
            label: Debug Information
            description: "
            Please run the \"/create debuginfo\" command in-game.
            This will copy a bunch of useful information that will greatly help with debugging.
            Please paste this information here.
            If this command does not exist, your version of Create is outdated.
            Please update to the latest version first.
            "
        validations:
            required: true

    -   type: markdown
        attributes:
            value: "Thank you for taking the time to report this and help improve Create!"
