name: Bug Report
description: For issues such as "X happens instead of Y"
title: "[BUG] *Replace with brief description of the issue*"
labels: "[bug]"
body:
  - type: markdown
    attributes:
      value: |
        For feedback and help with using the mod, check out the Create Discord! https://discord.gg/hmaD7Se
  - type: textarea
    id: bug-desc
    attributes:
      label: Description of the Bug
      description: Description of effects of the bug, and what actually happened.
      placeholder: |
        Causes X to do Z instead of Y.
    validations:
      required: true
  - type: textarea
    id: expected-behaviour
    attributes:
      label: Expected Behaviour
      description: What you expected to happen.
      placeholder: |
        1. Go to X
        2. Click on Y
        3. Z occurs
    validations:
      required: true
  - type: input
    id: version-info
    attributes:
      label: Create & Flywheel Versions
      placeholder: |
        Create 0.3.2c
        Flywheel 0.2.0
    validations:
      required: true
  - type: textarea
    id: screenshot
    attributes:
      label: Screenshots
      description: Screenshots of the issue, if applicable.
    validations:
      required: false
  - type: textarea
    id: log
    attributes:
      label: Logs
      description: Not required for all types of issues, do not include if not applicable.
      placeholder: Link from paste.gg, gist.github.com, etc.
    validations:
      required: false
  - type: textarea
    id: other-mods
    attributes:
      label: Extra Info
      description: What other mods do you have installed? For longer lists, use a Paste service, such as Github Gist.
      placeholder: |
        somerandommod-1.12.2-1.6.3
        someotherrandommod-1.3.4-1.56
    validations:
      required: true
  - type: textarea
    id: extra-info
    attributes:
      label: Extra Info
      description: Any extra info about your instance.
      placeholder: |
        Changed X to Y in create-common.toml
    validations:
      required: false
