blank_issues_enabled: true
contact_links:
    - name: I have a question!
      url: https://discord.gg/hmaD7Se
      about: Join us on Discord and ask the community.
    - name: I have a suggestion or idea!
      url: https://discord.gg/hmaD7Se
      about: These are best discussed with the community and submitted on Discord.
    - name: Talk to us on Discord.
      url: https://discord.gg/hmaD7Se
      about: Ask questions and get help from the community.
