blank_issues_enabled: true
contact_links:
    - name: I have an idea/suggestion!
      url: https://discord.gg/hmaD7Se
      about: These are best discussed with the community and submitted on Discord.
    - name: Talk to us on Discord
      url: https://discord.gg/hmaD7Se
      about: Ask questions and get help from the community.
