name: I have an idea/suggestion!
description: Submit your ideas and suggestions for consideration.
labels: [ "type: suggestion" ]
body:
    -   type: textarea
        attributes:
            label: Describe the Suggestion
            description: What should we add or change to make Create better? Please add screenshots or videos if they would be useful.
        validations:
            required: true
    
    -   type: markdown
        attributes:
            value: "Thank you for taking the time to make this suggestion and help improve Create!"
