name: "Label Actions"
on:
    issues:
        types: [labeled, unlabeled]
    pull_request_target:
        types: [labeled, unlabeled]

permissions:
    contents: read
    issues: write
    pull-requests: write
    discussions: write

jobs:
    action:
        runs-on: ubuntu-latest
        steps:
            - uses: dessant/label-actions@102faf474a544be75fbaf4df54e73d3c515a0e65 # Depend on an exact commit
              with:
                github-token: ${{ secrets.GITHUB_TOKEN }}
                config-path: '.github/config/label-actions.yml'
